### ISSUE TITLE
UnboundLocalError: local variable 'BigSecDict' referenced before assignment

### ISSUE THREAD

**Issue by jsmedmar** [raphael-group/THetA#10]

**Comment by jsmedmar** [comment]
You guys should point to a particular commit of the bnpy module...

I'm now getting this error:

luna:bnpy leukbot$ RunTHetA
Traceback (most recent call last):
  File "/ifs/work/leukgen/opt/theta/0.7/bin/../python/RunTHetA.py", line 39, in <module>
    from ClusteringBAF import clustering_BAF, group_to_meta_interval
  File "/ifs/work/leukgen/opt/theta/0.7/python/ClusteringBAF.py", line 29, in <module>
    import bnpy
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/bnpy/__init__.py", line 16, in <module>
    import allocmodel
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/bnpy/allocmodel/__init__.py", line 3, in <module>
    from mix.FiniteMixtureModel import FiniteMixtureModel
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/bnpy/allocmodel/mix/FiniteMixtureModel.py", line 8, in <module>
    from bnpy.util import NumericUtil
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/bnpy/util/NumericUtil.py", line 440, in <module>
    LoadConfig()
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/bnpy/util/NumericUtil.py", line 26, in LoadConfig
    Config = readConfigFileIntoDict(cfgfilepath, 'LibraryPrefs')
  File "/ifs/work/leukgen/bin/python/.virtualenvs/isabel2/lib/python2.7/site-packages/bnpy/util/NumericUtil.py", line 53, in readConfigFileIntoDict
    return BigSecDict
UnboundLocalError: local variable 'BigSecDict' referenced before assignment

**Comment by jsmedmar** [comment]
This was an installation error. Sorry!

**Comment by DarioS** [comment]
Can you close this issue, then?
