### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MOVBBirthMergeAlg'

### ISSUE THREAD

**Issue by ycl6** [raphael-group/THetA#19]
I installed THetA and bnpy using source files from github, but encounter this error:
```
/tools/THetA/bin/RunTHetA tumor.interval_count \
--TUMOR_FILE tumor.snp_formatted.txt --NORMAL_FILE normal.snp_formatted.txt \
--BAF --NUM_PROCESSES `nproc` --FORCE
```

```
Reading in query file...
Frac with potential copy numbers: 0.0734379924922
Reading SNP file at tumor.snp_formatted.txt
Reading SNP file at normal.snp_formatted.txt
Reading interval file at tumor.interval_count
Calculating BAFs
Determining heterozygosity.
Calculating BAFs.
First round of clustering...
Traceback (most recent call last):
  File "/tools/THetA/bin/../python/RunTHetA.py", line 514, in <module>
    main()
  File "/tools/THetA/bin/../python/RunTHetA.py", line 291, in main
    resultsfile2, boundsfile2 = run_fixed_N(2, args, intervals)
  File "/tools/THetA/bin/../python/RunTHetA.py", line 328, in run_fixed_N
    lengths, tumorCounts, normalCounts, m, upper_bounds, lower_bounds, clusterAssignments, numClusters, clusterMeans, normalInd = clustering_BAF(n, intervals=intervals, missingData=missingData, prefix=prefix, outdir=directory, numProcesses=num_processes)
  File "/tools/THetA/python/ClusteringBAF.py", line 99, in clustering_BAF
    metaData = generate_meta_data(intervals, byChrm, numProcesses, sampleName, generateData, outdir)
  File "/tools/THetA/python/ClusteringBAF.py", line 152, in generate_meta_data
    results = p.map(cluster_wrapper, zip(intervals, linearizedSampleName, linearizedChrm, linearizedGenerateData))
  File "/storage/miniconda2/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/storage/miniconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'module' object has no attribute 'MOVBBirthMergeAlg'

```

**Comment by AMMHasan** [comment]
Hit similar problem:

=================================================
Reading in query file...
Frac with potential copy numbers: 0.613192885512
Reading SNP file at ../mutation_file/Tumor_SNP.formatted.txt
Reading SNP file at ../mutation_file/Normal_SNP.formatted.txt
Reading interval file at ../Tumor.interval
Calculating BAFs
Determining heterozygosity.
Calculating BAFs.
First round of clustering...
Begin meta clustering...
Traceback (most recent call last):
  File "/THetA/bin/../python/RunTHetA.py", line 514, in <module>
    main()
  File "/THetA/bin/../python/RunTHetA.py", line 291, in main
    resultsfile2, boundsfile2 = run_fixed_N(2, args, intervals)
  File "/THetA/bin/../python/RunTHetA.py", line 328, in run_fixed_N
    lengths, tumorCounts, normalCounts, m, upper_bounds, lower_bounds, clusterAssignments, numClusters, clusterMeans, normalInd = clustering_BAF(n, intervals=intervals, missingData=missingData, prefix=prefix, outdir=directory, numProcesses=num_processes)
  File "/THetA/python/ClusteringBAF.py", line 106, in clustering_BAF
    metaMu, metaSigma, clusterAssignments, numPoints, numClusters = cluster(metaData, sampleName, sf=0.01, intervals=intervals)
  File "/THetA/python/ClusteringBAF.py", line 263, in cluster
    Data = format_data(data, sampleName, chrm)
  File "/THetA/python/ClusteringBAF.py", line 306, in format_data
    Data = bnpy.data.XData(X=npArray)
  File "/bnpy-dev/bnpy/data/XData.py", line 97, in __init__
    self._check_dims()
  File "/bnpy-dev/bnpy/data/XData.py", line 121, in _check_dims
    assert self.X.flags.owndata
AssertionError

**Comment by zhouyangyu** [comment]
@ycl6 You must use `bnpy-dev`. See https://michaelchughes@bitbucket.org/michaelchughes/bnpy-dev

**Comment by simozacca** [comment]
Yes, the current version of THetA only supports the `bnpy-dev` version of BNPY which is available here: https://bitbucket.org/michaelchughes/bnpy-dev/src/master/

There is also an easy fix that you can apply directly, please see the same topic in the HATCHet's repository at: https://github.com/raphael-group/hatchet/issues/3
