### ISSUE TITLE
Assertion error when having SNP inputs

### ISSUE THREAD

**Issue by YY-SONG0718** [raphael-group/THetA#25]
Dear maintainer,

I am experiencing an assertion error when running THetA2. This error only happens when I give --TUMOR_FILE and --NORMAL_FILE, without these inputs the program runs well. However, I would like to include them for better performance.

Testing the pipeline using files in THetA/example worked well too. 

```
Traceback (most recent call last):
  File "/bnpy-dev/THetA/bin/../python/RunTHetA.py", line 514, in <module>
    main()
  File "/bnpy-dev/THetA/bin/../python/RunTHetA.py", line 291, in main
    resultsfile2, boundsfile2 = run_fixed_N(2, args, intervals)
  File "/bnpy-dev/THetA/bin/../python/RunTHetA.py", line 328, in run_fixed_N
    lengths, tumorCounts, normalCounts, m, upper_bounds, lower_bounds, clusterAssignments, numClusters, clusterMeans, normalInd = clustering_BAF(n, intervals=intervals, missingData=missingData, prefix=prefix, outdir=directory, numProcesses=num_processes)
  File "/bnpy-dev/THetA/python/ClusteringBAF.py", line 106, in clustering_BAF
    metaMu, metaSigma, clusterAssignments, numPoints, numClusters = cluster(metaData, sampleName, sf=0.01, intervals=intervals)
  File "/bnpy-dev/THetA/python/ClusteringBAF.py", line 263, in cluster
    Data = format_data(data, sampleName, chrm)
  File "/bnpy-dev/THetA/python/ClusteringBAF.py", line 306, in format_data
    Data = bnpy.data.XData(X=npArray)
  File "/bnpy-dev/bnpy/data/XData.py", line 97, in __init__
    self._check_dims()
  File "/bnpy-dev/bnpy/data/XData.py", line 121, in _check_dims
    **assert self.X.flags.owndata
AssertionError**
```
Here is an example of my  --TUMOR_FILE, tab-separated:

#Chrm	Pos	Ref_Allele	Mut_Allele
1	1370651	24	5
1	2473951	37	4
1	3015890	20	5
1	3131698	40	3
1	4045065	18	5
1	4384916	26	4
1	4465499	29	5
1	4600606	27	3
1	4714444	41	4

I suspect that it is an issue related to the above input, but I cannot see the difference between mine and the example file. May I ask that what is the assertion for and what should I do?

Many thanks in advance.

Kind regards,

Yuyao

**Comment by matinslh** [comment]
Dear Yuyao,

Were you able to solve the problem?

Best, Matin
