### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Run'

### ISSUE THREAD

**Issue by xmzhuo** [raphael-group/THetA#27]
=================================================
Arguments are:
	Query File: sample.theta2.interval_count
	k: 3	tau: 2
	Output Directory: ./
	Output Prefix: sample
	Num Processes: 1
	Graph extension: .pdf
Valid sample for THetA analysis:
	Ratio Deviation: 0.1
	Min Fraction of Genome Aberrated: 0.05
	Program WILL cluster intervals.
=================================================
Reading in query file...
Frac with potential copy numbers: 0.162949234132
Reading SNP file at sample.tumor.snp_formatted.txt
Reading SNP file at sample.normal.snp_formatted.txt
Reading interval file at sample.theta2.interval_count
Calculating BAFs
Determining heterozygosity.
Calculating BAFs.
First round of clustering...
Traceback (most recent call last):
  File "/THetA/bin/../python/RunTHetA.py", line 514, in <module>
    main()
  File "/THetA/bin/../python/RunTHetA.py", line 291, in main
    resultsfile2, boundsfile2 = run_fixed_N(2, args, intervals)
  File "/THetA/bin/../python/RunTHetA.py", line 328, in run_fixed_N
    lengths, tumorCounts, normalCounts, m, upper_bounds, lower_bounds, clusterAssignments, numClusters, clusterMeans, normalInd = clustering_BAF(n, intervals=intervals, missingData=missingData, prefix=prefix, outdir=directory, numProcesses=num_processes)
  File "/THetA/python/ClusteringBAF.py", line 99, in clustering_BAF
    metaData = generate_meta_data(intervals, byChrm, numProcesses, sampleName, generateData, outdir)
  File "/THetA/python/ClusteringBAF.py", line 152, in generate_meta_data
    results = p.map(cluster_wrapper, zip(intervals, linearizedSampleName, linearizedChrm, linearizedGenerateData))
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
AttributeError: 'module' object has no attribute 'Run'

The enbvironment:
python 2.7.17
java:
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

packages:
alabaster (0.7.12)
asn1crypto (0.24.0)
Babel (2.9.1)
backports.functools-lru-cache (1.6.4)
backports.shutil-get-terminal-size (1.0.0)
bnpy (0.1.6, /bnpy)
certifi (2020.12.5)
chardet (4.0.0)
cryptography (2.1.4)
cycler (0.10.0)
Cython (0.29.23)
decorator (4.4.2)
docutils (0.17.1)
enum34 (1.1.6)
idna (2.6)
imagesize (1.2.0)
ipaddress (1.0.17)
ipython (5.10.0)
ipython-genutils (0.2.0)
Jinja2 (2.11.3)
joblib (0.14.1)
keyring (10.6.0)
keyrings.alt (3.0)
kiwisolver (1.1.0)
MarkupSafe (1.1.1)
matplotlib (2.2.5)
memory-profiler (0.57.0)
munkres (1.0.12)
numexpr (2.7.3)
numpy (1.16.6)
packaging (20.9)
pandas (0.24.2)
pathlib2 (2.3.5)
pexpect (4.8.0)
pickleshare (0.7.5)
Pillow (6.2.2)
pip (9.0.1)
prompt-toolkit (1.0.18)
psutil (5.8.0)
ptyprocess (0.7.0)
pycrypto (2.6.1)
Pygments (2.5.2)
pygobject (3.26.1)
pyparsing (2.4.7)
python-dateutil (2.8.1)
pytz (2021.1)
pyxdg (0.25)
requests (2.25.1)
scandir (1.10.0)
scikit-learn (0.20.4)
scipy (1.2.3)
SecretStorage (2.3.1)
setuptools (39.0.1)
simplegeneric (0.8.1)
six (1.11.0)
snowballstemmer (2.1.0)
Sphinx (1.8.5)
sphinx-gallery (0.4.0)
sphinxcontrib-websupport (1.1.2)
subprocess32 (3.5.4)
traitlets (4.3.3)
typing (3.10.0.0)
urllib3 (1.26.4)
wcwidth (0.2.5)
wheel (0.30.0)

**Comment by xmzhuo** [comment]
the newer bnpy (installed with pip) cause the issue, as long as the older bnpy-dev (with git) was used, it works fine.
